# Generated by Django 3.2.5 on 2021-07-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkmoa',
            old_name='direction',
            new_name='Direction',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='grade',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='guidemap',
            new_name='Guidemap',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='keyword',
            new_name='Keyword',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='longitude',
            new_name='Longitude',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='main_facility',
            new_name='Main_facility',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='num',
            new_name='Num',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='parcel_address',
            new_name='Parcel_address',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='park_area',
            new_name='Park_area',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='park_division',
            new_name='Park_division',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='park_name',
            new_name='Park_name',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='park_number',
            new_name='Park_number',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='park_overview',
            new_name='Park_overview',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='road_address',
            new_name='Road_address',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='shortcut',
            new_name='Shortcut',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='sporting_goods',
            new_name='Sporting_goods',
        ),
        migrations.RenameField(
            model_name='parkmoa',
            old_name='use_notes',
            new_name='Use_notes',
        ),
    ]
